### ISSUE TITLE
Features Checklist

### ISSUE THREAD

**Issue by gonz92alex** [Jolicost/ASW#33]
La implementació del cas d'ús previst per a la Sessió 02, revisada i corregida, si cal.

1. S'ha d'evitar donar d'alta urls repetits, encara que el títol sigui diferent. Tal com fa HN en aquests casos, si l'url ja existeix, es mostra la pàgina que visualitza aquella Contribució.

Implementació de la resta de funcionalitats:

2. Publicació de noves Contribucions de tipus "ask". Recordeu que si s'omplen alhora els camps "url" i "text", cal retornar un missatge d'error tal com fa HN.
3. Fer comentaris sobre Contribucions tipus "ask" i "url".
4. Visualització d'una Contribució, amb tots els seus  comentaris i les rèpliques a aquests.
5. Fer rèpliques sobre comentaris.
6. Votar/Desvotar Contribucions de tot tipus (url, ask, comentaris i rèpliques).
7. Registre / Login d'usuaris. Una diferència respecte al HN original: per fer el registre i el login heu d'utilitzar el "Sign In" extern de Google, Twitter, GitHub o similar (només un d'aquests). Mireu d'utilitzar gems que proporcionin aquesta funcionalitat. De fet, no cal que hi hagi diferència entre login i registre: quan l'usuari es loguegi per primera vegada es dóna d'alta com a usuari del sistema.
8. Veure el perfil de qualsevol usuari i veure/editar el perfil de l'usuari loguejat.
9. Llistats: a banda dels 2 llistats que ja heu fet per al cas d'ús de la Sessió 02,  feu-ne també: 
9.1 De la pàgina principal (menú superior): el llistat de Contribucions de tipus "ask" i el llistat de threads (= comments de l'usuari loguejat). La resta de llistats del HN original (comments, show, jobs) no són necessaris.
9.2. De la pàgina de perfil d'un usuari: els llistats submissions, comments, upvoted submissions (només de l'usuari loguejat) i upvoted comments (només de l'usuari loguejat).

**Comment by gonz92alex** [comment]
S'ha d'evitar donar d'alta urls repetits, encara que el títol sigui diferent. Tal com fa HN en aquests casos, si l'url ja existeix, es mostra la pàgina que visualitza aquella Contribució. 

### DONE

**Comment by gonz92alex** [comment]
2. Publicació de noves Contribucions de tipus "ask". Recordeu que si s'omplen alhora els camps "url" i "text", cal retornar un missatge d'error tal com fa HN.

### DONE

**Comment by gonz92alex** [comment]
3. Fer comentaris sobre Contribucions tipus "ask" i "url".

### DONE

**Comment by gonz92alex** [comment]
4. Visualització d'una Contribució, amb tots els seus comentaris i les rèpliques a aquest

### DONE

**Comment by gonz92alex** [comment]
5. Fer rèpliques sobre comentaris.

### DONE

**Comment by gonz92alex** [comment]
6. Votar/Desvotar Contribucions de tot tipus (url, ask, comentaris i rèpliques).


### DONE

**Comment by gonz92alex** [comment]
7. Registre / Login d'usuaris. Una diferència respecte al HN original: per fer el registre i el login heu d'utilitzar el "Sign In" extern de Google, Twitter, GitHub o similar (només un d'aquests). Mireu d'utilitzar gems que proporcionin aquesta funcionalitat. De fet, no cal que hi hagi diferència entre login i registre: quan l'usuari es loguegi per primera vegada es dóna d'alta com a usuari del sistema.

### DONE

**Comment by gonz92alex** [comment]
8. Veure el perfil de qualsevol usuari i veure/editar el perfil de l'usuari loguejat.

### DONE

**Comment by gonz92alex** [comment]
9. Llistats: a banda dels 2 llistats que ja heu fet per al cas d'ús de la Sessió 02, feu-ne també:
9.1 De la pàgina principal (menú superior): 
9.1.1 el llistat de Contribucions de tipus "ask" ### DONE
9.1.2 el llistat de threads (= comments de l'usuari loguejat). ### Cuando se haga el comments es lo mismo
9.1.3 La resta de llistats del HN original (comments, show, jobs) no són necessaris. ### DONE
9.2. De la pàgina de perfil d'un usuari: 
9.2.1 els llistats submissions, comments, upvoted submissions (només de l'usuari loguejat) i upvoted comments (només de l'usuari loguejat). ###  Falta comments

**Comment by Jolicost** [comment]
Comments DONE
