### ISSUE TITLE
API contribution Aldo

### ISSUE THREAD

**Issue by AldoFusterTurpin** [Jolicost/ASW#35]
post /api/contributions/:contributionId/comment
post /api/contributions
get /api/contributions/:id -> get contibucion

**Comment by Jolicost** [comment]
- post /api/contributions/:id/comment
- post /api/contributions -> crear contribucion -> Aldo
- get /api/contributions/:id -> get contibucion -> Aldo

**Comment by Jolicost** [comment]
POST /api/contributions
antiguo submit
BODY:
solo 3 atributos como maximo (url, text, title) Los otros deben ser ignorados
RETURNS:
Modelo de contribucion creado o existente (en el caso de las url ya existentes por ejemplo)
ERROR CODES:
400: Bad request (datos incorrectos o campos mínimos faltantes) Falta el titulo y el url
403: Token not provided (autorización no resolvible)
432: Se ha especificado a la vez CONTENT y URL en la contribucion
433: URL inválida (utilizar la libreria que checkea si la url es valida o no, referencia a mainController)
434: Contenido vacío (sólo ocurre si especificamos título pero no especificamos content) (diferente al error 400)
500: Internal server error

**Comment by Jolicost** [comment]
GET /api/contributions/:contributionId
RETURNS:
contribution model with all the attributes (every one of them)
ERROR CODES:
404: Contribution not found
500: Internal server error

**Comment by Jolicost** [comment]
DONE
