### ISSUE TITLE
API reparto

### ISSUE THREAD

**Issue by gonz92alex** [Jolicost/ASW#42]
post /api/contributions/:id/vote -> vota -> alejandro
post /api/contributions/:id/unvote -> desvota -> alejandro
post /api/contributions/:id/comment -> añade comentario -> Aldo
post /api/contributions -> crear contribucion -> Aldo

put /api/user/:id -> cambia el about -> Joan

get /api/user/:id -> obtiene el usuario -> Joan
get /api/contributions -> get contibuciones- Alejandro
get /api/contributions/:id -> get contibucion -> Aldo
get /api/contributions?user=:id%type=:type&sort=:sort%upvoted=:userid -> obtiene contribuciones filtradas -> Alejandro

**Comment by Jolicost** [comment]
Amagar atributs en respostes de contribucions:
-Cap atribut es invisible
Afegir atributs en respostes de contribucions:
-Number of comments (cal fer una consulta que ja esta preparada en els controladors anteriors)
-

**Comment by Jolicost** [comment]
Done
