### ISSUE TITLE
Implementació registre usuaris

### ISSUE THREAD

**Issue by AldoFusterTurpin** [Jolicost/ASW#9]

**Comment by AldoFusterTurpin** [comment]
Una diferència respecte al HN original: per fer el registre i el login heu d'utilitzar el "Sign In" extern de Google, Twitter, GitHub o similar (només un d'aquests).  De fet, no cal que hi hagi diferència entre login i registre: quan l'usuari es loguegi per primera vegada es dóna d'alta com a usuari del sistema.

**Comment by Jolicost** [comment]
Login amb servei extern (github) fet
